name: invariant_mobile
description: "The Invisible Identity Mobile Client"
version: 1.0.4+3
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  provider: ^6.1.1
  http: ^1.1.0
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0
  uuid: ^4.2.2
  permission_handler: ^11.3.0
  
  # Notifications & Scheduling (NEW)
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.3
  workmanager: ^0.9.0+3
  
  # Native Bridge
  native_keystore:
    path: ./packages/native_keystore

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# ICON CONFIGURATION
flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000" 
  adaptive_icon_foreground: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/